### ISSUE TITLE
Error on start!

### ISSUE THREAD

**Issue by ZerXGIT** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#120]
**Describe the bug**

**To Reproduce**
run run.py (python3.8 run.py)
4. See error:
Traceback (most recent call last):
  File "/home/testing/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 688, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/home/testing/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 280, in _get_conn
    return conn or self._new_conn()
  File "/home/testing/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 979, in _new_conn
    raise SSLError(
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/testing/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/testing/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/testing/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /helix/users?login=papaplatte (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 47, in <module>
    twitch_miner.mine(
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 97, in mine
    self.run(streamers, followers)
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 155, in run
    streamer.channel_id = self.twitch.get_channel_id(username)
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 359, in get_channel_id
    json_response = self.__do_helix_request(f"/users?login={streamer_username}")
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 389, in __do_helix_request
    response = self.twitch_login.session.get(url)
  File "/home/testing/.local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/testing/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/testing/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/testing/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.twitch.tv', port=443): Max retries exceeded with url: /helix/users?login=papaplatte (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Python version: 3.8.7

**Additional context**

**Comment by Tkd-Alex** [comment]
Please try to create a virtual env on your machine.
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/#how-to-use

**Comment by ZerXGIT** [comment]
Now there is a new Error when i run the script (python3 run.py): 

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 130
    f"Start session: '{self.session_id}'", extra={"emoji": ":bomb:"}
                                        ^
SyntaxError: invalid syntax

**Comment by Tkd-Alex** [comment]
We have already discussed this kind on problems in other issue.
You are currently using a wrong version of python

**Comment by ZerXGIT** [comment]
No I am running with (python3.8 run.py)
Next error:
24/03/21 15:43:33 - INFO - [login_flow]: You'll have to login to Twitch!
24/03/21 15:43:34 - ERROR - [login_flow]: Unknown error: {'error': 'Incorrect username or password.', 'error_code': 1014, 'error_description': 'user does not exist'}
Traceback (most recent call last):
  File "run.py", line 62, in <module>
    twitch_miner.mine(
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 123, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 135, in run
    self.twitch.login()
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 47, in login
    if self.twitch_login.login_flow():
  File "/home/testing/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 127, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 1014

**Comment by Element21** [comment]
Well, obviously ```'error_description': 'user does not exist'``` means that your username is not found on the twitch platform. This is probably a typo on your end.
