### ISSUE TITLE
I dont know what happend

### ISSUE THREAD

**Issue by juandeigo1014o** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#123]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Python version [e.g. 3.x]

**Additional context**

**Comment by juandeigo1014o** [comment]
Said this TypeError: 'NoneType' object is not subscriptable
27/03/21 19:18:54 - INFO - [on_message]: 🚀  +10 → Streamer(username=alonsolag, channel_id=425276286, channel_points=45.42k) - Reason: WATCH.
27/03/21 19:19:01 - ERROR - [on_message]: Exception raised for topic: video-playback-by-id and message: {'type': 'viewcount', 'server_time': 1616872740.450058, 'viewers': 93}
Traceback (most recent call last):
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 213, in on_message
    ws.streamers[streamer_index]
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 130, in check_streamer_online
    self.update_stream(streamer)
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 56, in update_stream
    stream_info = self.get_stream_info(streamer)
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 118, in get_stream_info
    if response["data"]["user"]["stream"] is None:
TypeError: 'NoneType' object is not subscriptable
27/03/21 19:19:31 - ERROR - [on_message]: Exception raised for topic: video-playback-by-id and message: {'type': 'viewcount', 'server_time': 1616872770.693319, 'viewers': 92}
Traceback (most recent call last):
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 213, in on_message
    ws.streamers[streamer_index]
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 130, in check_streamer_online
    self.update_stream(streamer)
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 56, in update_stream
    stream_info = self.get_stream_info(streamer)
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 118, in get_stream_info
    if response["data"]["user"]["stream"] is None:
TypeError: 'NoneType' object is not subscriptable
^C27/03/21 19:19:39 - INFO - [end]: CTRL+C Detected! Please wait just a moment!

**Comment by Tkd-Alex** [comment]
I don't know too :rofl: 
The error persist?

**Comment by kelukelol** [comment]
I've had the same issue, however, the script just kept running as it should be without any bugs, so I think that this issue just does nothing.
Windows 10
Python version 3.9.2

**Comment by 17Trust09** [comment]
have the same problem :) 
i takes a couple minutes and than it receives the first info that i got some points. 
so its look like ist fixxing it self, if you let stay in stat "error" condition
