### ISSUE TITLE
I get this error when. I don't know what caused it, the program was running for like a min then I got this. The program still runs I think cause I got a info message on a bet

### ISSUE THREAD

**Issue by alexjshepler** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#129]
02/04/21 12:05:17 - INFO - [set_offline]: 😴  Streamer(username=srb_ow, channel_id=53804043, channel_points=320) is Offline!
Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "D:\_Meme Shit\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 561, in sync_campaigns
    campaigns_details = self.__get_campaigns_details(
  File "D:\_Meme Shit\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 501, in __get_campaigns_details
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
  File "D:\_Meme Shit\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 501, in <lambda>
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
TypeError: string indices must be integers

**Comment by kelukelol** [comment]
Same issue here, 1st time I've got this issue it completely stopped the script, but after restarting my pc it runs after the issue without any issues. It's still a bug though.
Windows 10
Python version 3.9.2

**Comment by Tkd-Alex** [comment]
Duplicated of #128
