### ISSUE TITLE
An exception occurred while the script was running. After restarting the script I immediately get the same exception after it loaded the streamers.

### ISSUE THREAD

**Issue by Touka228** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#132]
Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "C:\Users\idobo\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\idobo\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\idobo\Downloads\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 569, in sync_campaigns
    campaigns_details = self.__get_campaigns_details(
  File "C:\Users\idobo\Downloads\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 497, in __get_campaigns_details
    chunks = create_chunks(campaigns)
TypeError: create_chunks() missing 1 required positional argument: 'n'

To Reproduce
Unclear, it seems that there is a drop that causes an issue.

Expected behavior
No exception in the console :)

Desktop (please complete the following information):

-Windows 10
-Python 3.9.2

Additional context
I'm on the latest version of the script (2f373bf)

**Comment by Tkd-Alex** [comment]
Duplicated of #128
You are not on the latest commit.

**Comment by Touka228** [comment]
Oh, exactly, I'm sorry for my stupidity.
