### ISSUE TITLE
campaings/inventory

### ISSUE THREAD

**Issue by LePrexis** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#133]
I get this error after Starting bot 

Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\User\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\User\Desktop\Twitch\V2\username\TwitchChannelPointsMiner\classes\Twitch.py", line 561, in sync_campaigns
    campaigns_details = self.__get_campaigns_details(
  File "C:\Users\User\Desktop\Twitch\V2\username\TwitchChannelPointsMiner\classes\Twitch.py", line 501, in __get_campaigns_details
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
  File "C:\Users\User\Desktop\Twitch\V2\username\TwitchChannelPointsMiner\classes\Twitch.py", line 501, in <lambda>
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
TypeError: string indices must be integers

**Comment by LePrexis** [comment]
Okay, I found the problem.

Open example.py In the streamer settings change "claim_drops=True" to false. I dont use drops so its fine for me.

**Comment by Tkd-Alex** [comment]
Duplicated of #128
