### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ozonestrike** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#139]
Hi,

I've got a big problem : 

Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "C:\Users\ME\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\ME\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ME\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 561, in sync_campaigns
    campaigns_details = self.__get_campaigns_details(
  File "C:\Users\ME\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 501, in __get_campaigns_details
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
  File "C:\Users\ME\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 501, in <lambda>
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
TypeError: string indices must be integers

Any ideas ?

**Comment by Tkd-Alex** [comment]
Are you on the latest commit?

**Comment by ozonestrike** [comment]
commit? sorry i don't understand :( explain me plz

**Comment by Tkd-Alex** [comment]
You are not on the latest version I suppose and this issue probably It's a duplicated of:
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/128
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/133
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/132
https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/129

**Comment by ozonestrike** [comment]
how to know the version Thx ;)

**Comment by ozonestrike** [comment]
C:\Users\ME>python --version
Python 3.9.2

C:\Users\ME>pip --version
pip 20.2.3 from c:\users\ME\appdata\local\programs\python\python39\lib\site-packages\pip (python 3.9)

It's ok ?

**Comment by testdev123456** [comment]
download the latest commit/version of the script and try again..

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/archive/refs/heads/master.zip

**Comment by ozonestrike** [comment]
Yes indeed it works now thx testdev123456 and Tkd-Alex.
