### ISSUE TITLE
 How to add browsers other

### ISSUE THREAD

**Issue by Ra91995** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#143]
Twitch-Channel-Points-Miner-v2 How to add browsers other than chrome firefox

Browser can only have one twitch account   is cookies

Sign in to another account 

Will appear keyerror:data

**Comment by Tkd-Alex** [comment]
I don't know if you are the same user that wrote me on Twitter.
As I already say you don't need to have multiple browser
1. All of your accounts seems to be had a captcha problem
2. You can always log out from the browser and use It for login with another user

**Comment by Ra91995** [comment]
chrome or firefox browser twitch account logout. Problems with logging in to another account 
12/04 18:27:00 - Exception raised for topic: video-playback-by-id and message: {'type': 'viewcount', 'server_time': 1618223219.623331, 'viewers': 2936}
Traceback (most recent call last):
  File "C:\Users\Ray\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 221, in on_message
    ws.twitch.check_streamer_online(
  File "C:\Users\Ray\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 141, in check_streamer_online
    self.update_stream(streamer)
  File "C:\Users\Ray\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 60, in update_stream
    stream_info = self.get_stream_info(streamer)
  File "C:\Users\Ray\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 122, in get_stream_info
    if response["data"]["user"]["stream"] is None:
KeyError: 'data'
