### ISSUE TITLE
Exception in thread Sync campaigns/inventory:

### ISSUE THREAD

**Issue by RowanF1** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#144]
After working very nice for weeks I got this message a few days ago. I reinstalled all requirements but I don't get it at work anymore. Does anyone has an idea?

Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 562, in sync_campaigns
    self.__get_drops_dashboard(status="ACTIVE")
  File "/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 501, in __get_campaigns_details
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
  File "/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 501, in <lambda>
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
TypeError: string indices must be integers

**Comment by Tkd-Alex** [comment]
Really? Again? :cry: 
Are you on the latest commit?

This situation is becoming stressful.
Maybe this issue is again  duplicated of:
#139
#128
#133
#132
#129

Please before open a new issue:
1. Make sure to have the latest commit
2. Check if another issue already exist
3. Use the issue template for opening a new one
