### ISSUE TITLE
Tool not running after restarting today

### ISSUE THREAD

**Issue by deion** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#146]
Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "C:\Users\D\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\D\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Twitch Tool\2-24 twitch update\1 baby\TwitchChannelPointsMiner\classes\Twitch.py", line 545, in sync_campaigns
    campaigns_details = self.__get_campaigns_details(
  File "E:\Twitch Tool\2-24 twitch update\1 baby\TwitchChannelPointsMiner\classes\Twitch.py", line 485, in __get_campaigns_details
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
  File "E:\Twitch Tool\2-24 twitch update\1 baby\TwitchChannelPointsMiner\classes\Twitch.py", line 485, in <lambda>
    return list(map(lambda x: x["data"]["user"]["dropCampaign"], response))
TypeError: string indices must be integers

**Comment by RakSrinaNa** [comment]
Probably #128 , get the latest version and try again.

**Comment by kelukelol** [comment]
The amount of people not reading the repo and searching for the same issue is truly disappointing :/

**Comment by RakSrinaNa** [comment]
That's why I proposed in #48 to enable discussions. All these "support" issues could be transformed as discussions and fit a bit more the nature of what is asked. And that'd help to keep the issues for what they really are, issues.

An example of discussions quite used can be found here: https://github.com/keepassxreboot/keepassxc/discussions

And honestly it's easier to handle user support in those, or just simple discussions. Easy to find when an answer has been given etc.
There can even be some "mini tutorials" like Q&A for frequent steps of people not knowing how to update the script etc. All that without cluttering too much the readme that is already quite long.
