### ISSUE TITLE
Captcha login fails

### ISSUE THREAD

**Issue by emanresu2** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#181]
This has never worked on both my PCs. I always waited until console login was available again, but it has been like 20 hours now and it's still not.
I tried reinstalling python, but I'm not sure what else to do.

```
21/05 17:45:51 - You'll have to login to Twitch!
21/05 17:45:52 - Console login unavailable (CAPTCHA solving required).
What browser do you use? Chrome (1), Firefox (2), Other (3): 1
Please login inside your browser of choice (NOT incognito mode) and press Enter...
21/05 17:46:48 - Loading cookies saved on your computer...
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\browser_cookie3\__init__.py", line 267, in load
    cur.execute('SELECT host_key, path, secure, expires_utc, name, value, encrypted_value '
sqlite3.OperationalError: no such column: secure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Desktop\Miner\run.py", line 62, in <module>
    twitch_miner.mine(
  File "C:\Users\user\Desktop\Miner\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 123, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "C:\Users\user\Desktop\Miner\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 135, in run
    self.twitch.login()
  File "C:\Users\user\Desktop\Miner\TwitchChannelPointsMiner\classes\Twitch.py", line 51, in login
    if self.twitch_login.login_flow():
  File "C:\Users\user\Desktop\Miner\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 139, in login_flow
    self.set_token(self.login_flow_backup())
  File "C:\Users\user\Desktop\Miner\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 167, in login_flow_backup
    cookie_jar = browser_cookie3.chrome(domain_name=twitch_domain)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\browser_cookie3\__init__.py", line 592, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\browser_cookie3\__init__.py", line 271, in load
    cur.execute('SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value '
sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v10↕R¶ �c���S��1~K��/�wS��►*♣j!☺`����►|�♣GB�∟~V�&q6J`�� ►��@�w��>�}>⌂�B����B�u�♫�]��pX`^���Y����{��'
Exception ignored in: <function ChromiumBased.__del__ at 0x00000210A729A4C0>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\browser_cookie3\__init__.py", line 255, in __del__
    os.remove(self.tmp_cookie_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmphpw7qa4_.sqlite'
```

**Comment by RakSrinaNa** [comment]
Maybe try with another browser ? Maybe a recent update of the browser you're using broke something.

**Comment by Tkd-Alex** [comment]
@emanresu2 Any news? Solved? Can we close this issue?

**Comment by zenko2** [comment]
у меня таже проблема  Firefox тоже самле выдает 
29/09/21 16:38:14 - INFO - [login_flow]: Console login unavailable (CAPTCHA solving required).
What browser do you use? Chrome (1), Firefox (2), Other (3): 1
Please login inside your browser of choice (NOT incognito mode) and press Enter...
есть ли решения проблемы?

**Comment by 13Quavo** [comment]
Have same issue on Termux. https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/518

**Comment by 13Quavo** [comment]
> @emanresu2 Any news? Solved? Can we close this issue?

Anything to do with browser_cookie3? 

I have the same issue on Termux. can't log in because Console login is unavailable and then the captcha solvin required throws error.
