### ISSUE TITLE
What to do

### ISSUE THREAD

**Issue by Sergey28n** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#187]
- Exception raised for topic: community-points-user-v1 and message: {'type': 'points-earned', 'data': {'timestamp': '2021-05-24T18:33:04.148396395Z', 'channel_id': '426223598', 'point_gain': {'user_id': '657288664', 'channel_id': '426223598', 'total_points': 10, 'baseline_points': 10, 'reason_code': 'WATCH', 'multipliers': []}, 'balance': {'user_id': '657288664', 'channel_id': '426223598', 'balance': 22030}}}
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 182, in on_message
    ws.streamers[streamer_index].persistent_series(
  File "/data/data/com.termux/files/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 190, in persistent_series
    self.__save_json("series", event_type=event_type)
  File "/data/data/com.termux/files/home/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 205, in __save_json
    json_data = json.load(open(fname, "r")) if os.path.isfile(fname) else {}
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/data/data/com.termux/files/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/data/data/com.termux/files/usr/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 748 column 11 (char 15782)

**Comment by Tkd-Alex** [comment]
It's permanent? Frequently or randomly?

**Comment by Tkd-Alex** [comment]
You could try to remove the json with history points for analytics
I think some It's corrupted

**Comment by Tkd-Alex** [comment]
Same error on #221 
The problem It's in you analytics folder
