### ISSUE TITLE
Something went wrong unable to continue with betting - Fillable box not avaible

### ISSUE THREAD

**Issue by StephanBruh** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#2]
Getting this error on the bets currently, watching forsen.

18/01/21 21:12:06 - ERROR - [__execute_script]: Failed to execute: document.querySelector("button[data-test-selector="prediction-checkout-active-footer__input-type-toggle"]").click();
Traceback (most recent call last):
  File "D:\bets\TwitchChannelPointsMiner\classes\TwitchBrowser.py", line 150, in __execute_script
    self.browser.execute_script(javascript_code)
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 634, in execute_script
    return self.execute(command, {
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Stephan\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: missing ) after argument list
  (Session info: headless chrome=87.0.4280.141)

Yes I am on the latest commit

**Comment by Tkd-Alex** [comment]
???
