### ISSUE TITLE
Repl.it error

### ISSUE THREAD

**Issue by Huguitis** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#212]
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/runner/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/runner/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 25, in <module>
    from TwitchChannelPointsMiner.classes.WebSocketsPool import WebSocketsPool
  File "/home/runner/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 13, in <module>
    from TwitchChannelPointsMiner.classes.TwitchWebSocket import TwitchWebSocket
  File "/home/runner/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/TwitchWebSocket.py", line 5, in <module>
    from websocket import WebSocketApp, WebSocketConnectionClosedException
ImportError: cannot import name 'WebSocketApp' from 'websocket' (/opt/virtualenvs/python3/lib/python3.8/site-packages/websocket/__init__.py)
exit status 1

**Comment by Tkd-Alex** [comment]
Are you sure that you are starting `run.py` in the correct folder?

**Comment by Huguitis** [comment]
fixed the problem was that repl.it uninstalls the packages at the end of the project
