### ISSUE TITLE
Traceback Error on raspbian

### ISSUE THREAD

**Issue by Claxl** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#237]
Hello there, I'm using this bot on my raspberry, but when I run my script it gave me this 

Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 70
    username: str,
            ^
SyntaxError: invalid syntax

On Windows, it work properly

**Comment by IDerFlohI** [comment]
I got the same thing today on my android mobile. Tried to run it but same error. And for me it also works properly on windows

**Comment by RakSrinaNa** [comment]
Do you use python3? (And not python 2?)

**Comment by Claxl** [comment]
Yes, do you suggest using python2?

**Comment by RakSrinaNa** [comment]
The project is only compatible with python 3.6+. So a good place to start is check if you at least have the version.
