### ISSUE TITLE
Errors and problems with strategies

### ISSUE THREAD

**Issue by Yishaqel** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#3]
Good evening, first of all, I have to say that I have no idea about programming, just enough to make it work. I tried with all the possible strategies and always the program bet on the one that has less percentage of winning.

Also I receive this type of errors constantly:

`--- Logging error ---
Traceback (most recent call last):
  File "C:\Python\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f527' in position 95: character maps to <undefined>
Call stack:
  File "C:\Python\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "C:\notra\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\TwitchBrowser.py", line 320, in place_bet
-- Logging error ---
Traceback (most recent call last):
  File "C:\Python\lib\logging\__init__.py", line 1084, in emit
    stream.write(msg + self.terminator)
  File "C:\Python\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in position 97: character maps to <undefined>
Call stack:
  File "C:\Python\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Python\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\notra\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 60, in <lambda>
    self.thread_ws = threading.Thread(target=lambda: self.ws.run_forever())
  File "C:\Python\lib\site-packages\websocket\_app.py", line 306, in run_forever
    dispatcher.read(self.sock.sock, read, check)
  File "C:\Python\lib\site-packages\websocket\_app.py", line 66, in read
    if not read_callback():
  File "C:\Python\lib\site-packages\websocket\_app.py", line 290, in read
    self._callback(self.on_message, data)
  File "C:\Python\lib\site-packages\websocket\_app.py", line 346, in _callback
    callback(self, *args)
  File "C:\notra\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 147, in on_message
`

Thank you for the effort you are putting into this utility.

**Comment by Tkd-Alex** [comment]
- Which version of python?
`python --version`
- Are you on Windows machine?
- The other functionality work correctly?

If you can please try a few hours with:
```python
browser_settings=BrowserSettings(
        .... # Other values
        do_screenshot=True
        save_html=True
)
```

**Comment by Yishaqel** [comment]
Python 3.8.3 and Windows 10 with the latest updates. I believe that the other functions work correctly except the betting strategies. I will try to update this thread after activating the options mentioned.

**Comment by Tkd-Alex** [comment]
Because the problem seems to be related with the `logging` module, I don't know if the other logs are printed (and writes in file) correctly

**Comment by Tkd-Alex** [comment]
Anyway the options do screenshot and save html will help us to debug, nothing else

**Comment by Tkd-Alex** [comment]
If you can please share also a .log file

**Comment by Yishaqel** [comment]
I will try to check why the program is not betting on a stream now, then I will upload everything necessary to get a solution. Any suggestions for where to upload the files?

**Comment by Tkd-Alex** [comment]
You can create a .zip and upload here or if you want reach me on Discord `Tkd-Alex#1666`
