### ISSUE TITLE
error

### ISSUE THREAD

**Issue by IsGris** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#338]
**Describe the bug**
as a result of this error, one streamer is not recognized

**Desktop (please complete the following information):**
 - OS: Windows
 - Python version 3.9,6

**Additional context**
Error with GQLOperations (ReportMenuItem): HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000025E63048730>, 'Connection to gql.twitch.tv timed out. (connect timeout=None)'))

and after first

Exception in thread Sync campaigns/inventory:
Traceback (most recent call last):
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] Попытка установить соединение была безуспешной, т.к. от другого компьютера за требуемое время не получен нужный отклик, или было разорвано уже установленное соединение из-за неверного отклика уже подключенного компьютера

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000017CE86D0BE0>, 'Connection to gql.twitch.tv timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017CE86D0BE0>, 'Connection to gql.twitch.tv timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IsGris\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 217, in post_gql_request
    response = requests.post(
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000017CE86D0BE0>, 'Connection to gql.twitch.tv timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\IsGris\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\IsGris\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 612, in sync_campaigns
    campaigns_details = self.__get_campaigns_details(
  File "C:\Users\IsGris\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 534, in __get_campaigns_details
    response = self.post_gql_request(json_data)
  File "C:\Users\IsGris\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 232, in post_gql_request
    f"Error with GQLOperations ({json_data['operationName']}): {e}"
TypeError: list indices must be integers or slices, not str

**Comment by Tkd-Alex** [comment]
It's just a connection error

**Comment by IsGris** [comment]
> It's just a connection error

but i have good internet speed and i don't think this is my internet speed
![image](https://user-images.githubusercontent.com/83012795/141472523-2ca13aef-fb90-4936-972c-a32f5ad2b748.png)

**Comment by Tkd-Alex** [comment]
Sometimes happen, a request to Twitch can fail :)
