### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by TheOnlyWayUp** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#350]
I'm not sure what's causing this, I just left the farmer running on VPS for 2 days and these errors started showing up, I was alerted to it when I tried opening it in the browser and saw an error message.

Traceback (most recent call last):
  File "/root/channelPointsMiner/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 181, in on_message
  File "/root/channelPointsMiner/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 219, in persistent_series
  File "/root/channelPointsMiner/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 239, in __save_json
FileNotFoundError: [Errno 2] No such file or directory: '/root/channelPointsMiner/analytics/TheOnlyWayLeft/itzsubz_.json'
23/11/21 12:00:02 - ERROR - [on_message]: Exception raised for topic: community-points-user-v1 and message: {'type': 'points-earned', 'data': {'timestamp': '2021-11-23T12:00:02.81170663Z', 'channel_id': '158661281', 'point_gain': {'user_id': '735983317', 'channel_id': '158661281', 'total_points': 10, 'baseline_points': 10, 'reason_code': 'WATCH', 'multipliers': []}, 'balance': {'user_id': '735983317', 'channel_id': '158661281', 'balance': 4790}}}

Traceback (most recent call last):
  File "/root/channelPointsMiner/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 181, in on_message
  File "/root/channelPointsMiner/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 219, in persistent_series
  File "/root/channelPointsMiner/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 239, in __save_json
FileNotFoundError: [Errno 2] No such file or directory: '/root/channelPointsMiner/analytics/TheOnlyWayLeft/itzsubz_.json'
23/11/21 12:02:53 - INFO - [stop]: 💬  Leave IRC Chat: itzsubz_
23/11/21 12:02:53 - INFO - [set_offline]: 😴  Streamer(username=itzsubz_, channel_id=158661281, channel_points=4.79k) is Offline!
23/11/21 17:28:02 - ERROR - [log_exception]: Exception on / [GET]

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/root/channelPointsMiner/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 38, in index
  File "/root/channelPointsMiner/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 19, in streamers_available
FileNotFoundError: [Errno 2] No such file or directory: '/root/channelPointsMiner/analytics/TheOnlyWayLeft'

**Comment by Tkd-Alex** [comment]
Missing JSON file for analytics
I suppose you have deleted the file or the folder

**Comment by TheOnlyWayUp** [comment]
That's the thing, I haven't. I just left it running on my VPS for a few days and when I came back, this was in console. Could there be another cause?
