### ISSUE TITLE
Internal Server Error - Analytics

### ISSUE THREAD

**Issue by ThoLaNL** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#373]
When i try to access the analytics website, it shows an internal server error. the log file shows the following error:

29/12/21 22:53:46 - ERROR - [log_exception]: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python310\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python310\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Python310\lib\site-packages\TwitchChannelPointsMiner\classes\AnalyticsServer.py", line 35, in index
    return render_template(
  File "C:\Python310\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Python310\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python310\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python310\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: charts.html

**Comment by Tkd-Alex** [comment]
Make sure to have downloaded all the files

**Comment by ThoLaNL** [comment]
oke i fixed the problem after downloading the files from: GITHUB/Twitch-Channel-Points-Miner-v2/assets/ and stored it in: C:\Python310\Lib\site-packages\Twitch_Channel_Points_Miner_v2-2.0.7-py3.10.egg-info\assets. (used the pip installer)
