### ISSUE TITLE
Bet doesn't work after few days

### ISSUE THREAD

**Issue by Clement49** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#381]
Hello there,
Thanks for the usefull script, kinda new but made it work after the youtube video explenations 
I used the script for a week, bet were working fine, but now it just collect the points.
I restart it every morning with a task scheduler

 - OS: Windows 10 Pro
 - Python version 3.9.8

This is the line i wrote : 
`Streamer("XXXXX", settings=StreamerSettings(make_predictions=True  , follow_raid=True , claim_drops=True  , watch_streak=True , bet=BetSettings(strategy=Strategy.SMART      , percentage=5 , stealth_mode=True,  percentage_gap=20 , max_points=10000   , filter_condition=FilterCondition(by=OutcomeKeys.TOTAL_USERS,      where=Condition.LTE, value=200 ) ) )),
   `
I watch moslty FPS player so bets are mostly either win or loose

**Comment by Clement49** [comment]
So now i have this after every bet 
`Exception raised for topic: community-points-user-v1 and message: {'type': 'points-earned', 'data': {'timestamp': '2022-01-05T15:57:09.234414832Z', 'channel_id': '638511570', 'point_gain': {'user_id': '90052916', 'channel_id': '638511570', 'total_points': 10, 'baseline_points': 10, 'reason_code': 'WATCH', 'multipliers': []}, 'balance': {'user_id': '90052916', 'channel_id': '638511570', 'balance': 128050}}}
Traceback (most recent call last):
  File "C:\Users\Clément\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 181, in on_message
    ws.streamers[streamer_index].persistent_series(
  File "C:\Users\Clément\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\entities\Streamer.py", line 219, in persistent_series
    self.__save_json("series", event_type=event_type)
  File "C:\Users\Clément\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\entities\Streamer.py", line 234, in __save_json
    json_data = json.load(open(fname, "r")) if os.path.isfile(fname) else {}
  File "C:\Python\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
