### ISSUE TITLE
Windows 11 run.py not working

### ISSUE THREAD

**Issue by potovzuc** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#410]
hello, there is no problem when I was on windows 10 before, but when I switched to 11, I started getting this error.

Traceback (most recent call last):
  File "C:\Users\yusuf\Documents\Twitch-Channel-Points-Miner-v2-master\run.py", line 5, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "C:\Users\yusuf\Documents\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "C:\Users\yusuf\Documents\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 24, in <module>
    from TwitchChannelPointsMiner.classes.WebSocketsPool import WebSocketsPool
  File "C:\Users\yusuf\Documents\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 7, in <module>
    from dateutil import parser
  File "C:\Python310\lib\site-packages\dateutil\parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

**Comment by Tkd-Alex** [comment]
Reinstall python and requirements

**Comment by potovzuc** [comment]
not working

**Comment by Frixas** [comment]
Was able to solve the problem?  I also have only
10 windows

**Comment by bricep** [comment]
This is working for me on Windows 11. Can you try using the exact run.py from the main page and see if that works? Otherwise reinstall Python & requirements.
