### ISSUE TITLE
Former working Miner v2 suddenly closes right after start "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by gitgryllus** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#440]
The miner worked like a charm but from today on when I open the miner, it closes after 1 second. This shows up in IDLE:

>>> 
==== RESTART: C:\Users\jakob\Downloads\Twitch-Channel-Points-Miner-v2\run.py ===
03/03 13:56:55 - Start session: '52f6ea84-d03d-4458-b20d-4ad271aa06a9'
[0mTraceback (most recent call last):[0m
[0m  File "C:\Users\jakob\Downloads\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 122, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
[0m[0m  File "C:\Users\jakob\Downloads\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 153, in run
    followers_array = self.twitch.get_followers()
[0m[0m  File "C:\Users\jakob\Downloads\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 185, in get_followers
    return [
[0m[0m  File "C:\Users\jakob\Downloads\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 186, in <listcomp>
    fw["user"]["login"]
[0m[0mTypeError: 'NoneType' object is not subscriptable
[0m[0m
>>>

**Comment by gitgryllus** [comment]
When i run it through IDLE now, it works. Doesn't work directly though.
