### ISSUE TITLE
Analytics got reset

### ISSUE THREAD

**Issue by i-have-two-moms** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#485]
**Describe the bug**
The new Analytics page looks nice and I like having the names on the side with the option to sort them rather than having them on the top with a side scroll, however since it switch to the newer version all my Analytics have been reset and it no longer shows days prior to the upgrade.

**Expected behavior**
Analytics page should have kept the previous records from before the upgrade.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python version 3.10

**Additional context**
I was using a much older version of this repository, but upgraded to the recent one. I copied over all the log files from the previous one.

**Comment by helloeverything1** [comment]
Mine migrated over just fine, but I think you do have to set the date so try that?

**Comment by i-have-two-moms** [comment]
> Mine migrated over just fine, but I think you do have to set the date so try that?

Set the date on the website? I tried that before but it doesn't go back past the point where I updated.

**Comment by ColinShark** [comment]
> I copied over all the log files from the previous one.

The log files themselves are irrelevant. They only give an output of what happened. You'll want to have copied the analytics from `<project_root>/analytics/<username>/`. The json files at that location actually contain the events and timestamps for the analytics webpage.

**Comment by i-have-two-moms** [comment]
> > I copied over all the log files from the previous one.
> 
> The log files themselves are irrelevant. They only give an output of what happened. You'll want to have copied the analytics from `<project_root>/analytics/<username>/`. The json files at that location actually contain the events and timestamps for the analytics webpage.

I just copied the files from the old analytics into the new one and it basically breaks it. The Analytics website won't show the streamer names and the graph will just say "loading". The console will also throw out a bunch of errors. 

>Traceback (most recent call last):
  File "C:\Users\Toaster\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Toaster\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Toaster\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Toaster\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Python\Coding\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\AnalyticsServer.py", line 145, in streamers
    [
  File "D:\Python\Coding\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\AnalyticsServer.py", line 146, in <listcomp>
    {"name": s, "points": get_challenge_points(s)}
  File "D:\Python\Coding\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\AnalyticsServer.py", line 112, in get_challenge_points
    datas = read_json(streamer, return_response=False)
  File "D:\Python\Coding\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\AnalyticsServer.py", line 105, in read_json
    json.load(open(os.path.join(path, streamer)))
  File "C:\Users\Toaster\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Toaster\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Toaster\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Toaster\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
