### ISSUE TITLE
Doesn’t work on Rpi

### ISSUE THREAD

**Issue by Flenser42** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#508]
When I run “run.py” on my Raspberry Pi this error comes.
pi@raspberrypi:~/Twitch-Channel-Points-Miner-v2 $ python run.py
Traceback (most recent call last):
  File "/home/pi/Twitch-Channel-Points-Miner-v2/run.py", line 5, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/home/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 14, in <module>
    from TwitchChannelPointsMiner.classes.AnalyticsServer import AnalyticsServer
  File "/home/pi/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 8, in <module>
    import pandas as pd
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/home/pi/.local/lib/python3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject

**To Reproduce**
1. Go to 'Twitch-Channel-Points-Miner-v2'
2. Click on 'python run.py 
3. See error

**Expected behavior**
Run as normal

**Desktop (please complete the following information):**
 - OS: Raspian 11(bullseye)
 
 - Python version 3.9.2

**Comment by RealMoondancer** [comment]
Based on [this](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp) StackOverflow Article try upgrading your numpy version using `python3 -m pip install --upgrade numpy`

**Comment by Cerberus-ik** [comment]
I am having the exact same issues after updating to the newest version.

The suggested workaround didn't work for me.

**Comment by RealMoondancer** [comment]
We tried finding a solution later in a vc and found a stackoverflow articke which solved the problem. After updating numpy we needed to install some depdecies. If a command errors or the module is not found, just skip it.
`sudo apt-get install libcblas-dev
sudo apt-get install libhdf5-dev
sudo apt-get install libhdf5-serial-dev
sudo apt-get install libatlas-base-dev
sudo apt-get install libjasper-dev 
sudo apt-get install libqtgui4 
sudo apt-get install libqt4-test
sudo apt-get install libilmbase-dev
sudo apt-get install libopenexr-dev
sudo apt-get install libgstreamer1.0-dev
sudo apt-get install libavcodec-dev
sudo apt-get install libavformat-dev
sudo apt-get install libswscale-dev
sudo apt-get install libwebp-dev`

**Comment by RealMoondancer** [comment]
What is the traceback that is printed for you?

**Comment by Cerberus-ik** [comment]
`Traceback (most recent call last):
  File "/home/pi/twitch/docker/phil.py", line 5, in <module>
    from TwitchChannelPointsMiner.classes.Chat import ChatPresence
ImportError: cannot import name 'ChatPresence' from 'TwitchChannelPointsMiner.classes.Chat' (/home/pi/.local/lib/python3.9/site-packages/TwitchChannelPointsMiner/classes/Chat.py)`

And yes I updated numpy and the docker images
