### ISSUE TITLE
ImportError: cannot import name 'WebSocketApp' from 'websocket'

### ISSUE THREAD

**Issue by Gioix12** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#529]
Traceback (most recent call last):
  File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\run.py", line 5, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\TwitchChannelPointsMiner\__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 24, in <module>
    from TwitchChannelPointsMiner.classes.WebSocketsPool import WebSocketsPool
  File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 13, in <module>
    from TwitchChannelPointsMiner.classes.TwitchWebSocket import TwitchWebSocket
  File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\TwitchChannelPointsMiner\classes\TwitchWebSocket.py", line 5, in <module>
    from websocket import WebSocketApp, WebSocketConnectionClosedException
ImportError: cannot import name 'WebSocketApp' from 'websocket' (C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\websocket\__init__.py)

This is the error it shows after running the run.py file
How can i fix it

**Comment by ColinShark** [comment]
<details><summary>For better readability please wrap code/console output in triple backticks:</summary>

    ```
    code/output
    ```
will yield:
```
Traceback (most recent call last):
File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\run.py", line 5, in
from TwitchChannelPointsMiner import TwitchChannelPointsMiner
File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\TwitchChannelPointsMiner\__init__.py", line 3, in
from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 24, in
from TwitchChannelPointsMiner.classes.WebSocketsPool import WebSocketsPool
File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 13, in
from TwitchChannelPointsMiner.classes.TwitchWebSocket import TwitchWebSocket
File "C:\Users\User\Twitch-Channel-Points-Miner-v2-User\TwitchChannelPointsMiner\classes\TwitchWebSocket.py", line 5, in
from websocket import WebSocketApp, WebSocketConnectionClosedException
ImportError: cannot import name 'WebSocketApp' from 'websocket' (C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\websocket\__init__.py)
```
</details>

---

> This is the error it shows after running the run.py file

How exactly are you running your `run.py`? Make sure you both install dependencies and run the program with the same Python version. For example like this:

```
python3 -m pip install -Ur requirements.txt
python3 run.py
```
