### ISSUE TITLE
Error logged at some point without any user action, whole program broken after a restart

### ISSUE THREAD

**Issue by MAXOUXAX** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#549]
**Describe the bug**
Don't know what happened, but an error occured and got logged, and the bot stopped working (no more logs, but it was still on)
```
16/07/22 20:11:20 - ERROR - [log_exception]: Exception on /json/mistermv.json [GET]
Traceback (most recent call last):
  File "/home/container/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/container/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/container/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/container/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/container/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 95, in read_json
    filter_datas(
  File "/home/container/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 44, in filter_datas
    datetime.strptime(start_date, "%Y-%m-%d").timestamp() * 1000
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'NaN-NaN-NaN' does not match format '%Y-%m-%d'
16/07/22 20:11:28 - ERROR - [log_exception]: Exception on /json/lestream.json [GET]
Traceback (most recent call last):
  File "/home/container/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/container/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/container/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/container/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/container/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 95, in read_json
    filter_datas(
  File "/home/container/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 44, in filter_datas
    datetime.strptime(start_date, "%Y-%m-%d").timestamp() * 1000
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'NaN-NaN-NaN' does not match format '%Y-%m-%d'
16/07/22 20:11:30 - ERROR - [log_exception]: Exception on /json/lestream.json [GET]
Traceback (most recent call last):
  File "/home/container/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/container/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/container/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/container/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/container/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 95, in read_json
    filter_datas(
  File "/home/container/TwitchChannelPointsMiner/classes/AnalyticsServer.py", line 44, in filter_datas
    datetime.strptime(start_date, "%Y-%m-%d").timestamp() * 1000
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'NaN-NaN-NaN' does not match format '%Y-%m-%d'
```

After restarting the program, I thought everything would be fine, but I got some huge errors everytime something is trying to be logged, don't know if that's related but might be.
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/home/container/TwitchChannelPointsMiner/logger.py", line 113, in format
    record.msg = emoji.emojize(
TypeError: emojize() got an unexpected keyword argument 'use_aliases'
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
Message: 'Analytics running on http://0.0.0.0:2583/'
Arguments: None
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1079, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 923, in format
    return fmt.format(record)
  File "/home/container/TwitchChannelPointsMiner/logger.py", line 113, in format
    record.msg = emoji.emojize(
TypeError: emojize() got an unexpected keyword argument 'use_aliases'
Call stack:
  File "/usr/local/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
Message: "Start session: '256a3885-a1c0-40d7-9a0e-8ae94d5cf019'"
Arguments: None
```

**To Reproduce**
I have no idea how to reproduce this error since I did not do anything and it occured randomly during execution.

**Expected behavior**
No error should happen

**Desktop (please complete the following information):**
 - OS: Debian 11 but that's kinda irrelevant
 - Python 3.9

**Comment by MAXOUXAX** [comment]
Can be temporarily fixed by setting `emoji` to `False` in the recorder settings.

**Comment by Tkd-Alex** [comment]
you could try with `pip install --upgrade emoji`
