### ISSUE TITLE
Logging error? 

### ISSUE THREAD

**Issue by ItsCerv** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#550]
**Describe the bug**
randomly got this error while running the script, I tried running a fresh script on my laptop but got the same error 

`--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\ryan4\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\ryan4\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\ryan4\OneDrive\Desktop\miner\TwitchChannelPointsMiner\logger.py", line 113, in format
    record.msg = emoji.emojize(
TypeError: emojize() got an unexpected keyword argument 'use_aliases'
Call stack:
  File "C:\Users\ryan4\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\ryan4\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\ryan4\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
Message: 'xqc (371.92k points) is Offline!'`

**Comment by MAXOUXAX** [comment]
Seems like it is a duplicate of #549
