### ISSUE TITLE
Error on "python run.py"

### ISSUE THREAD

**Issue by KakaoIstGesund92** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#611]
Hi everybody.

On Startup "python run.py" on my Raspberry Pi 4 I always get following error. Can someone help?

```
28/09/22 16:09:35 - INFO - [login_flow]: You'll have to login to Twitch!
Traceback (most recent call last):
28/09/22 16:09:40 - ERROR - [login_flow]: Unknown error: {'error': 'Oops! We encountered an unexpected error. Please try again.', 'error_code': 5027, 'error_description': 'client blocked from this operation'}
  File "/home/pi/run.py", line 78, in <module>
    twitch_miner.mine(
  File "/home/pi/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 150, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "/home/pi/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 168, in run
    self.twitch.login()
  File "/home/pi/TwitchChannelPointsMiner/classes/Twitch.py", line 56, in login
    if self.twitch_login.login_flow():
  File "/home/pi/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 129, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 5027

```

**Comment by mrk59** [comment]
Check this : https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/606#issuecomment-1256839239

**Comment by bsdanu** [comment]
Hi, I am a noob
Your second step is
"Enter the folder and enter this command: docker build -t twitchbot:experimental ."
Where do i enter this command - cmd or anything else, can you explain briefly or make a tutorial.

**Comment by rdavydov** [comment]
@bsdanu I guess you're not building a Docker image and just want to run it (not in a container)? Download a zip file with the latest release, unpack it, edit example.py with your data and settings, then run it with python.
