### ISSUE TITLE
client blocked from this operation

### ISSUE THREAD

**Issue by Varga-Levente** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#628]
16/10/22 17:09:32 - INFO - [run]: Start session: '0b5969d7-8e48-44d9-b5b3-9ebae380a4c8'
16/10/22 17:09:32 - INFO - [login_flow]: You'll have to login to Twitch!
16/10/22 17:09:32 - ERROR - [login_flow]: Unknown error: {'error': 'Oops! We encountered an unexpected error. Please try again.', 'error_code': 5027, 'error_description': 'client blocked from this operation'}
Traceback (most recent call last):
  File "run.py", line 78, in <module>
    twitch_miner.mine(
  File "/home/sysadmin/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 150, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "/home/sysadmin/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 168, in run
    self.twitch.login()
  File "/home/sysadmin/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 56, in login
    if self.twitch_login.login_flow():
  File "/home/sysadmin/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 129, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 5027

**Comment by rdavydov** [comment]
Old client is blocked, try my fixed version https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/

**Comment by Varga-Levente** [comment]
Thanks
