### ISSUE TITLE
Prediction doesn't work.

### ISSUE THREAD

**Issue by ugc0203** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#636]
**Describe the bug**
Prediction doesn't work, just a message is printed

**To Reproduce**
1. just start point miner
2. When prediction starts, only a message is output.
3. message:
Exception raised for topic: predictions-user-v1 and message: {'type': 'prediction-made', 'data': {'timestamp': '2022-10-22T09:23:18.990141198Z', 'prediction': {'id': '37e81d4ef87f0ab7cddde80c3f499abb12fcbd326e14ccde008c2640e7b8be93', 'event_id': '86a8172f-ae93-4b2f-b141-c70eefd624af', 'outcome_id': '8d72928a-8b9a-4960-851a-914e819b7b03', 'channel_id': '49045679', 'points': 6424, 'predicted_at': '2022-10-22T09:23:18.936619641Z', 'updated_at': '2022-10-22T09:23:18.936619641Z', 'user_id': '485785947', 'result': None, 'user_display_name': None}}}
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\WebSocketsPool.py", line 369, in on_message
    f"Decision: {event_prediction.bet.decision['choice']} - {event_prediction.title}",
KeyError: 'choice'

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python version [Python 3.10.7]

There may be some inaccuracies due to the use of translations.

**Comment by rdavydov** [comment]
Could you specify a version of the miner?

**Comment by ArtemBay** [comment]
> Could you specify a version of the miner? What link did you download it from?

Same problem. Using pip version. Downloaded 18.10

**Comment by ArtemBay** [comment]
And one more error with prediction
```py
Traceback (most recent call last):
  File "/home/kkunfin/.local/lib/python3.8/site-packages/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 322, in on_message
    points = event_prediction.parse_result(
  File "/home/kkunfin/.local/lib/python3.8/site-packages/TwitchChannelPointsMiner/classes/entities/EventPrediction.py", line 69, in parse_result
    points["placed"] = self.bet.decision["amount"]
KeyError: 'amount'
```

**Comment by AdamT20054** [comment]
> And one more error with prediction
> 
> ```python
> Traceback (most recent call last):
>   File "/home/kkunfin/.local/lib/python3.8/site-packages/TwitchChannelPointsMiner/classes/WebSocketsPool.py", line 322, in on_message
>     points = event_prediction.parse_result(
>   File "/home/kkunfin/.local/lib/python3.8/site-packages/TwitchChannelPointsMiner/classes/entities/EventPrediction.py", line 69, in parse_result
>     points["placed"] = self.bet.decision["amount"]
> KeyError: 'amount'
> ```

Please can you post your settings

**Comment by ArtemBay** [comment]
StreamerSettings?

**Comment by ArtemBay** [comment]
```py
    streamer_settings=StreamerSettings(
        make_predictions=True,
        follow_raid=True,
        claim_drops=True,
        watch_streak=True,
        chat=ChatPresence.ONLINE,
        bet=BetSettings(
            strategy=Strategy.SMART,
            percentage=25,
            percentage_gap=20,
            max_points=50000,
            stealth_mode=True,
            delay_mode=DelayMode.FROM_END,
            delay=6,
            minimum_points=300,
            filter_condition=FilterCondition(
                by=OutcomeKeys.TOTAL_USERS,
                where=Condition.LTE,
                value=400
            )
        )
    )
```

**Comment by ArtemBay** [comment]
After installing @bossoq fork all works fine

**Comment by rdavydov** [comment]
@ArtemBay not all - you won't get points for raids and bonuses, because unfortunately his fork is also outdated, like the pip version that you mentioned.

You can check my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2 if you are interested.
I've fixed this issue, plus added switchable analytics and console_username option.

**Comment by ktc64** [comment]
I tried your fork rdavy but I'm getting these line errors for threading.py and it doesn't seem to want to actually claim drops. There's one in this picture just stuck at 100% https://i.imgur.com/6XbCCtA.png I'm kind of over my head with these kinds of things, I just hopped into the issue's section today to finally try and fix my drops not claiming. It's been busted for a while now.
