### ISSUE TITLE
Oops! We encountered an unexpected error. Please try again.

### ISSUE THREAD

**Issue by peedro11232** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#645]
**Describe the bug**
01/11 21:40:38 - You'll have to login to Twitch!
Traceback (most recent call last):
01/11 21:40:38 - Unknown error: {'error': 'Oops! We encountered an unexpected error. Please try again.', 'error_code': 5027, 'error_description': 'client blocked from this operation'}
  File "C:\Users\1\Desktop\1\run.txt", line 78, in <module>
    twitch_miner.mine(
  File "C:\Users\1\Desktop\1\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 150, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "C:\Users\1\Desktop\1\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 168, in run
    self.twitch.login()
  File "C:\Users\1\Desktop\1\TwitchChannelPointsMiner\classes\Twitch.py", line 56, in login
    if self.twitch_login.login_flow():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\Desktop\1\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 129, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 5027

**To Reproduce**
1. Go to 'cmd, cd twitch-points, py run.txt '

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 
 - Python version 3.11.0 Git version 2.38.1

**Additional context**

**Comment by rdavydov** [comment]
Fixed in my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/

**Comment by peedro11232** [comment]
> Fixed in my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/

01/11 21:54:56 - You'll have to login to Twitch!
01/11 21:54:56 - Console login unavailable (CAPTCHA solving required).
Traceback (most recent call last):

hi thanks, but is the same error changing the "console login unavailable"

**Comment by rdavydov** [comment]
Because it is not available anymore. You can't login with console anymore. Read the release notes: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/1.4.0

**Comment by JappeHallunken** [comment]
I rerun `pip install -U -r requirements.txt` and it worked again for me without the errors.

**Comment by rdavydov** [comment]
> I rerun `pip install -U -r requirements.txt` and it worked again for me without the errors.

That's great! It is always useful to fully read the release notes. ;)

**Comment by JappeHallunken** [comment]
No, I got the same error as OP.  I read the release notes, but I'm on a headless machine, so I decided not to update. I also habe no chrome installed on my RPi. I just rerun what I said and the login error went away.

**Comment by JappeHallunken** [comment]
But despite the infos in the release notes (I'm on a headless machine) it still works without chrome and without a display (I don't even have a DE running on that thing). So I'm confused what happend, but I'm glad the error went away.

**Comment by rdavydov** [comment]
What version we're talking about? So much has happened since then.

If you already have a "console" cookie - previous miner version should claim bonuses just fine.

**Comment by JappeHallunken** [comment]
Indeed I still have the cookie file in my cookies folder.
How can I find out which version I'm currently running?

**Comment by rdavydov** [comment]
> Indeed I still have the cookie file in my cookies folder. How can I find out which version I'm currently running?

Open `TwitchChannelPointsMiner\__init__.py` in a text editor.

You should see something like:
`__version__ = "2.1.1"`

**Comment by JappeHallunken** [comment]
OK I'm on 2.1.1.

**Comment by rdavydov** [comment]
> OK I'm on 2.1.1.

It's not OK. 😉

It means you're using an outdated version. Current version from my fork is 1.5.0 https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases

Yeah, I know it is lower than 2, but it is actually "Miner-v2-1.5.0" and I had to start a different count.

**Comment by JappeHallunken** [comment]
Wow, I didn't expect such a high rates of updates ;)
