### ISSUE TITLE
help

### ISSUE THREAD

**Issue by BarboPT** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#685]
INFO - [login_flow]: You'll have to login to Twitch!
Traceback (most recent call last):
  File "run.py", line 89, in <module>
06/01/23 23:18:46 - ERROR - [login_flow]: Unknown error: {'error': 'Please update your app to continue', 'error_code': 5023, 'error_description': 'client is not supported for this feature'}
    twitch_miner.mine(
  File "/home/runner/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 150, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "/home/runner/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 168, in run
    self.twitch.login()
  File "/home/runner/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 56, in login
    if self.twitch_login.login_flow():
  File "/home/runner/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 129, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 5023

i try install the package twitch-channel-points but give this problem " Requirement already satisfied"

**Comment by jurmarr** [comment]
did you try using this special release? 
https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2/releases/tag/1.5.4

**Comment by BarboPT** [comment]
nop , i use the normal installation

**Comment by rdavydov** [comment]
Fixed in my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2
