### ISSUE TITLE
Running into issues with windows install

### ISSUE THREAD

**Issue by jeff-actual** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#703]
C:\Users\Desktop\Twitch-Channel-Points-Miner-v2>run.py
Enter Twitch password for User: 19/02 20:06:59 - Start session: '7b8e5a6d-0aaf-432c-80b2-d4f96ee1b4dd'
19/02 20:06:59 - You'll have to login to Twitch!

Traceback (most recent call last):
  File "C:\Users\Desktop\Twitch-Channel-Points-Miner-v2\run.py", line 78, in <module>
19/02 20:07:03 - Unknown error: {'error': 'Please update your app to continue', 'error_code': 5023, 'error_description': 'client is not supported for this feature'}
    twitch_miner.mine(
  File "C:\Users\Desktop\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 150, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "C:\Users\Desktop\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 168, in run
    self.twitch.login()
  File "C:\Users\Desktop\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 56, in login
    if self.twitch_login.login_flow():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Desktop\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 129, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 5023

**Comment by jeff-actual** [comment]
Nevermind. I was using an outdated build.
