### ISSUE TITLE
Error 5023

### ISSUE THREAD

**Issue by Ahwxorg** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#712]
**Describe the bug:**
TCPM v2 ran fine without any issues before I had to reinstall my server due to SSD corruption. After reinstalling and getting the exact same run.py from my persistant storage, and setting up the exact same configuration, it does not work anymore. I get error 5023, see logs below.

**Steps to reproduce:**
```sh
git clone https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2
Twitch-Channel-Points-Miner-v2/
ls
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
python run.py
*logs as shown below happen*
```

**Expected behavior:**
TCPM v2 works and mines channel points after asking password and Twitch email key.

**Server:**
 - OS: [Debian 12/sid]
 - Python version [3.11.2]

**Additional context**

```sh
(venv) twitch@snowflake:~/Twitch-Channel-Points-Miner-v2$ python run.py
06/03/23 10:37:15 - INFO - [run]: 🌐  Analytics running on http://0.0.0.0:5000/
06/03/23 10:37:15 - INFO - [run]: 💣  Start session: '*session*'
Enter Twitch password for *username*: 06/03/23 10:37:15 - INFO - [login_flow]: You'll have to login to Twitch! *insert password*

Traceback (most recent call last):
  File "/home/twitch/Twitch-Channel-Points-Miner-v2/run.py", line 111, in <module>
06/03/23 10:37:27 - ERROR - [login_flow]: Unknown error: {'error': 'Please update your app to continue', 'error_code': 5023, 'error_description': 'client is not supported for this feature'}
    twitch_miner.mine(
  File "/home/twitch/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 150, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "/home/twitch/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 168, in run
    self.twitch.login()
  File "/home/twitch/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 56, in login
    if self.twitch_login.login_flow():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/twitch/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 129, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 5023
(venv) twitch@snowflake:~/Twitch-Channel-Points-Miner-v2$
```

**Comment by rdavydov** [comment]
Fixed in my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2

**Comment by Ahwxorg** [comment]
Why isn't this in the head repo?

**Comment by Ahwxorg** [comment]
@Tkd-Alex ?

**Comment by Tkd-Alex** [comment]
> Why isn't this in the head repo?

Because no one have done a pull request 🙂

**Comment by Ahwxorg** [comment]
Can't you merge it? There's multiple people asking for a fix on this issue on other issues.

**Comment by Flotss** [comment]
I have this problem too, I use your fork @rdavydov and it's work, but many people will want to use @Tkd-Alex repository.
Can you merge it ?

**Comment by rdavydov** [comment]
@Flotss why can't you just use my repo? Tkd even updated the README and explicitly wrote: **This project is not mainted anymore, please use the updated repo at https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2**
