### ISSUE TITLE
Error 5023 - Semi new to DockerCompose

### ISSUE THREAD

**Issue by Excelling-At-Excel** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#714]
2023-03-20 00:26:19 twitchfarm-miner-1  | 20/03/23 05:26:19 - INFO - [run]: Start session: '86c5b180-e5d5-4e80-805f-4aae131214e8'
2023-03-20 00:26:19 twitchfarm-miner-1  | 20/03/23 05:26:19 - INFO - [login_flow]: You'll have to login to Twitch!
2023-03-20 00:26:19 twitchfarm-miner-1  | Traceback (most recent call last):
2023-03-20 00:26:19 twitchfarm-miner-1  |   File "run.py", line 78, in <module>
2023-03-20 00:26:19 twitchfarm-miner-1  | 20/03/23 05:26:19 - ERROR - [login_flow]: Unknown error: {'error': 'Please update your app to continue', 'error_code': 5023, 'error_description': 'client is not supported for this feature'}
2023-03-20 00:26:19 twitchfarm-miner-1  |     twitch_miner.mine(
2023-03-20 00:26:19 twitchfarm-miner-1  |   File "/usr/src/app/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 150, in mine
2023-03-20 00:26:19 twitchfarm-miner-1  |     self.run(streamers=streamers, blacklist=blacklist, followers=followers)
2023-03-20 00:26:19 twitchfarm-miner-1  |   File "/usr/src/app/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 168, in run
2023-03-20 00:26:19 twitchfarm-miner-1  |     self.twitch.login()
2023-03-20 00:26:19 twitchfarm-miner-1  |   File "/usr/src/app/TwitchChannelPointsMiner/classes/Twitch.py", line 56, in login
2023-03-20 00:26:19 twitchfarm-miner-1  |     if self.twitch_login.login_flow():
2023-03-20 00:26:19 twitchfarm-miner-1  |   File "/usr/src/app/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 129, in login_flow
2023-03-20 00:26:19 twitchfarm-miner-1  |     raise NotImplementedError(
2023-03-20 00:26:19 twitchfarm-miner-1  | NotImplementedError: Unknown TwitchAPI error code: 5023

I'm somewhat new to DockerCompose, so I apologize if there is something easy i'm missing, but i'm not sure what is erroring out exactly.  Any help would be greatly appreciated.

**Comment by rdavydov** [comment]
Fixed in my fork https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2
