### ISSUE TITLE
idk what I do wrong, pls help me

### ISSUE THREAD

**Issue by ghost** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#739]
03/08 19:28:38 - You'll have to login to Twitch!
Traceback (most recent call last):
03/08 19:28:39 - Unknown error: {'error': 'Please update your app to continue', 'error_code': 5023, 'error_description': 'client is not supported for this feature'}
  File "C:\Users\mrche\Desktop\Twitch-Channel-Points-Miner-v2-master\run.py", line 78, in <module>
    twitch_miner.mine(
  File "C:\Users\mrche\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 150, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "C:\Users\mrche\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 168, in run
    self.twitch.login()
  File "C:\Users\mrche\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\Twitch.py", line 56, in login
    if self.twitch_login.login_flow():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mrche\Desktop\Twitch-Channel-Points-Miner-v2-master\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 129, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 5023

C:\Users\mrche\Desktop\Twitch-Channel-Points-Miner-v2-master>

**Comment by Armi1014** [comment]
I have the exact same error. But idk how to fix it.

**Comment by ghost** [comment]
> I have the exact same error. But idk how to fix it.

I just installed the latest version and it worked

**Comment by Armi1014** [comment]
Yea, it works for me also. Im happy that it works for you
