### ISSUE TITLE
Auto claim drops

### ISSUE THREAD

**Issue by Vizis** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#740]
Just a quick question, cause im cunfused a bit, Is the auto claim drops option works or not.
i Run the script on screen on linux so option "claim drops on start up" doest help for me, and there is a option in streemer settings " claim_drops" but it's commented as it doest work... and to have it turned 'false' [# We can't filter rewards base on stream. Set to False for skip viewing counter increase and you will never obtain a drop reward from this script. Issue #21], with this option True bot not claim the drops that's for sure
also got error at the start
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/miner/TwitchChannelPointsMiner/classes/Twitch.py", line 799, in sync_campaigns
    self.__get_drops_dashboard(status="ACTIVE")
  File "/home/miner/TwitchChannelPointsMiner/classes/Twitch.py", line 700, in __get_drops_dashboard
    filter(lambda x: x["status"] == status.upper(), campaigns))
TypeError: 'NoneType' object is not iterable
```

as in the #681 i just deleted my cookie file and generated new to check if it helps, but points areclaimed correcly so cookies should be fine..

**Comment by bijkomune** [comment]
I have the same error, but normally scores.

**Comment by jowilksasella** [comment]
Same question. Working on claiming points, but I need to claim drops by going to inventory and clicking that button.
