### ISSUE TITLE
help me please !!

### ISSUE THREAD

**Issue by Belalmohamed12** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#773]
**Describe the bug**
PS C:\Users\vrko3\Desktop\Twitch-Channel-Points-Miner-v2> python run.py
25/04 17:36:46 - 💣  Start session: '6974d9a1-48ff-45d5-836d-157d13c6d8bd'
25/04 17:36:46 - You'll have to login to Twitch!
Traceback (most recent call last):
  File "C:\Users\vrko3\Desktop\Twitch-Channel-Points-Miner-v2\run.py", line 78, in <module>
25/04 17:36:47 - Unknown error: {'error': 'Please update your app to continue', 'error_code': 5023, 'error_description': 'client is not supported for this feature'}
    twitch_miner.mine(
  File "C:\Users\vrko3\Desktop\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 150, in mine
    self.run(streamers=streamers, blacklist=blacklist, followers=followers)
  File "C:\Users\vrko3\Desktop\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 168, in run
    self.twitch.login()
  File "C:\Users\vrko3\Desktop\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 56, in login
    if self.twitch_login.login_flow():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vrko3\Desktop\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\TwitchLogin.py", line 129, in login_flow
    raise NotImplementedError(
NotImplementedError: Unknown TwitchAPI error code: 5023

**To Reproduce**
1. Go to 'cmd'
2. Write 'python run.py'
3. See error

**Desktop (please complete the following information):**
 - OS: Windows 11 pro 23h2
 - Python version 3.12.3
![image](https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/assets/39450756/9e5af07c-4c05-45b2-9070-1dff87e7786a)

**Comment by Guliveer** [comment]
In the error message, you have blatantly written what to do

**Comment by Hendrik292** [comment]
Up2Date Repository: https://github.com/rdavydov/Twitch-Channel-Points-Miner-v2
