### ISSUE TITLE
Empty inventory

### ISSUE THREAD

**Issue by unknownmp7** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#84]
Error code 
```
C:\Users\USERNAME\Twitch-Channel-Points-Miner-v2>python run.py
21/02/21 02:33:41 - INFO - [run]: 💣  Start session: '----------------------------------------'
Traceback (most recent call last):
  File "C:\Users\USERNAME\Twitch-Channel-Points-Miner-v2\run.py", line 47, in <module>
    twitch_miner.mine(
  File "C:\Users\USERNAME\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 97, in mine
    self.run(streamers, followers)
  File "C:\Users\USERNAME\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\TwitchChannelPointsMiner.py", line 112, in run
    self.twitch.claim_all_drops_from_inventory()
  File "C:\Users\USERNAME\Twitch-Channel-Points-Miner-v2\TwitchChannelPointsMiner\classes\Twitch.py", line 192, in claim_all_drops_from_inventory
    for campaign in inventory["dropCampaignsInProgress"]:
TypeError: 'NoneType' object is not iterable
```

i tried to reinstall the whole thing and it didn't worked

**Comment by Tkd-Alex** [comment]
Can you share the page (screenshot) of your twitch inventory?

**Comment by Element21** [comment]
Sorry for jumping in here, but I am having this error also. I have nothing in my inventory. Just pulled the latest few commits and it broke.

**Comment by Element21** [comment]
Oh, it's just an error saying you cannot iterate through an empty array (since there is nothing in the users inventory.)

**Comment by Element21** [comment]
I have a working patch. Will open a pr soon.

**Comment by Tkd-Alex** [comment]
That's surprise me, how it's possible that your inventory is empty 🤔

**Comment by Tkd-Alex** [comment]
If It's possibile someone can post this debug line?

https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/pull/68#issuecomment-782674867

**Comment by unknownmp7** [comment]
> That's surprise me, how it's possible that your inventory is empty 🤔

I checked it, its not empty

**Comment by Tkd-Alex** [comment]
In fact I think the #85 fix the script just for prevent the crash but can broke the drops collection 

I need the debug logs, please.

**Comment by unknownmp7** [comment]
```21/02/21 19:39:19 - INFO - TwitchChannelPointsMiner.TwitchChannelPointsMiner - [run]: Start session: '---------------'```

this is the only thing in the logs file

**Comment by Tkd-Alex** [comment]
You are probably missing:
`file_level​=​logging​.​DEBUG`

In your settings

**Comment by unknownmp7** [comment]
```
21/02/21 22:38:41 - INFO - TwitchChannelPointsMiner.TwitchChannelPointsMiner - [run]: Start session: '-------'
21/02/21 22:38:41 - DEBUG - urllib3.connectionpool - [_new_conn]: Starting new HTTPS connection (1): gql.twitch.tv:443
21/02/21 22:38:42 - DEBUG - urllib3.connectionpool - [_make_request]: https://gql.twitch.tv:443 "POST /gql HTTP/1.1" 200 697
21/02/21 22:38:42 - DEBUG - TwitchChannelPointsMiner.classes.Twitch - [post_gql_request]: Data: -------------------
```

**Comment by Tkd-Alex** [comment]
Yes but If you redact the important part how I can help you?😂 You should share the entire part without replacing ----

**Comment by unknownmp7** [comment]
```21/02/21 22:49:10 - INFO - TwitchChannelPointsMiner.TwitchChannelPointsMiner - [run]: Start session: '------------------'
21/02/21 22:49:10 - DEBUG - urllib3.connectionpool - [_new_conn]: Starting new HTTPS connection (1): gql.twitch.tv:443
21/02/21 22:49:10 - DEBUG - urllib3.connectionpool - [_make_request]: https://gql.twitch.tv:443 "POST /gql HTTP/1.1" 200 697
21/02/21 22:49:10 - DEBUG - TwitchChannelPointsMiner.classes.Twitch - [post_gql_request]: Data: {'operationName': 'Inventory', 'variables': {}, 'extensions': {'persistedQuery': {'version': 1, 'sha256Hash': 'e0765ebaa8e8eeb4043cc6dfeab3eac7f682ef5f724b81367e6e55c7aef2be4c'}}}, Status code: 200, Content: {"data":{"currentUser":{"id":"133398156","inventory":{"drops":{"nodes":[{"awardedAt":"2020-04-12T06:35:06Z","node":{"id":"515ced06-e551-8e5a-b903-d55ef234f9d6","game":{"id":"516575","name":"VALORANT","__typename":"Game"},"imageURL":"https://gds-vhs-drops-campaign-images.twitch.tv/items/931fd934-2149-4a85-a6d8-2190aa4439f3/515ced06-e551-8e5a-b903-d55ef234f9d6-80x80.jpg","name":"VALORANT","__typename":"Drop"},"__typename":"DropAward","__typename":"DropAward"},{"awardedAt":"2020-10-29T22:32:37Z","node":{"id":"4a3b5afa-14e9-4657-bcef-5a6c32cce668","game":{"id":"488634","name":"Don't Starve Together","__typename":"Game"},"imageURL":"https://gds-vhs-drops-campaign-images.twitch.tv/items/39716808-5c46-41fc-89fb-66ccbbf12421/4a3b5afa-14e9-4657-bcef-5a6c32cce668-80x80.jpg","name":"Don't Starve Together","__typename":"Drop"},"__typename":"DropAward","__typename":"DropAward"},{"awardedAt":"2020-10-29T21:02:38Z","node":{"id":"4a3b5afa-14e9-4657-bcef-5a6c32cce668","game":{"id":"488634","name":"Don't Starve Together","__typename":"Game"},"imageURL":"https://gds-vhs-drops-campaign-images.twitch.tv/items/39716808-5c46-41fc-89fb-66ccbbf12421/4a3b5afa-14e9-4657-bcef-5a6c32cce668-80x80.jpg","name":"Don't Starve Together","__typename":"Drop"},"__typename":"DropAward","__typename":"DropAward"},{"awardedAt":"2020-10-31T14:29:30Z","node":{"id":"4a3b5afa-14e9-4657-bcef-5a6c32cce668","game":{"id":"488634","name":"Don't Starve Together","__typename":"Game"},"imageURL":"https://gds-vhs-drops-campaign-images.twitch.tv/items/39716808-5c46-41fc-89fb-66ccbbf12421/4a3b5afa-14e9-4657-bcef-5a6c32cce668-80x80.jpg","name":"Don't Starve Together","__typename":"Drop"},"__typename":"DropAward","__typename":"DropAward"},{"awardedAt":"2020-10-04T10:17:17Z","node":{"id":"94648b0e-500b-45a5-9f77-02d4316769df","game":{"id":"21779","name":"League of Legends","__typename":"Game"},"imageURL":"https://gds-vhs-drops-campaign-images.twitch.tv/items/931fd934-2149-4a85-a6d8-2190aa4439f3/94648b0e-500b-45a5-9f77-02d4316769df-80x80.jpg","name":"Worlds 2020 Viewership","__typename":"Drop"},"__typename":"DropAward","__typename":"DropAward"},{"awardedAt":"2020-02-20T15:11:27Z","node":{"id":"1f68e68f-0290-ae18-a4de-589f8f27bc85","game":{"id":"21779","name":"League of Legends","__typename":"Game"},"imageURL":"https://gds-vhs-drops-campaign-images.twitch.tv/items/931fd934-2149-4a85-a6d8-2190aa4439f3/1f68e68f-0290-ae18-a4de-589f8f27bc85-80x80.jpg","name":"Clash Ticket","__typename":"Drop"},"__typename":"DropAward","__typename":"DropAward"}],"__typename":"UserDropAwardConnection"},"dropCampaignsInProgress":null,"gameEventDrops":[],"__typename":"Inventory"},"__typename":"User"}},"extensions":{"durationMilliseconds":61,"operationName":"Inventory","requestID":"01EZ3271X5GWPB1XHK5JCCT36X"}}
```

heres the whole thing
