### ISSUE TITLE
i need help to use in cloud google, syntax error invalid syntax 

### ISSUE THREAD

**Issue by juandeigo1014o** [Tkd-Alex/Twitch-Channel-Points-Miner-v2#89]
i use cloud google 
root@server01:~/Twitch-Channel-Points-Miner-v2# python run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 60
    username: str,

and i have ubuntu 18.04 with python 3

**Comment by Tkd-Alex** [comment]
Read https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/86 https://github.com/Tkd-Alex/Twitch-Channel-Points-Miner-v2/issues/88

**Comment by juandeigo1014o** [comment]
when i use python3 run.py said me
root@servidor03:~/Twitch-Channel-Points-Miner-v2# python3 run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/__init__.py", line 3, in <module>
    from .TwitchChannelPointsMiner import TwitchChannelPointsMiner
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 15, in <
module>
    from TwitchChannelPointsMiner.classes.entities.Streamer import (
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/entities/Streamer.py", line 4, in <
module>
    from TwitchChannelPointsMiner.classes.entities.Bet import BetSettings
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/entities/Bet.py", line 5, in <modul
e>
    from millify import millify
ModuleNotFoundError: No module named 'millify'

i have python3 version Python 3.6.9

**Comment by Tkd-Alex** [comment]
You have to install all requirements with `pip install -r requirements.txt`
Please read the README before open an issue

**Comment by juandeigo1014o** [comment]
i install the requirements but said me this ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
and when i try with python3 run.py said syntax errorr

**Comment by Tkd-Alex** [comment]
Create a virtualenv, It's a problem of your configuration and not script related

**Comment by juandeigo1014o** [comment]
ok but you can help to do this with cloud google?

**Comment by Tkd-Alex** [comment]
```sh
pip install virtualenv
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
python run.py
```

**Comment by juandeigo1014o** [comment]
it works but i have the problem that when i go to put the password y can not write

**Comment by Tkd-Alex** [comment]
I don't know if the problem It's the same of #77 , but I want to remember that password input is hidden

**Comment by juandeigo1014o** [comment]
what does that mean? that i need to open a new session?

**Comment by juandeigo1014o** [comment]
ok i do and i enter but said me that sect a browser, i select, i login in this browser and said this, 
Please login inside your browser of choice (NOT incognito mode) and press Enter...
23/02/21 19:54:09 - INFO - [login_flow_backup]: Loading cookies saved on your computer...
Traceback (most recent call last):
  File "run.py", line 61, in <module>
    followers=False                    # Automatic download the list of your followers (unable to set custom settings for you followers list)
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 97, in mine
    self.run(streamers, followers)
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/TwitchChannelPointsMiner.py", line 109, in run
    self.twitch.login()
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/Twitch.py", line 44, in login
    if self.twitch_login.login_flow():
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 122, in login_flow
    self.set_token(self.login_flow_backup())
  File "/root/Twitch-Channel-Points-Miner-v2/TwitchChannelPointsMiner/classes/TwitchLogin.py", line 153, in login_flow_backup
    cookie_jar = browser_cookie3.firefox(domain_name=twitch_domain)
  File "/root/Twitch-Channel-Points-Miner-v2/venv/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 616, in firefox
    return Firefox(cookie_file, domain_name).load()
  File "/root/Twitch-Channel-Points-Miner-v2/venv/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 455, in __init__
    cookie_file = cookie_file or self.find_cookie_file()
  File "/root/Twitch-Channel-Points-Miner-v2/venv/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 528, in find_cookie_file
    raise BrowserCookieError('Failed to find Firefox cookie')
browser_cookie3.BrowserCookieError: Failed to find Firefox cookie

**Comment by juandeigo1014o** [comment]
ok works, thanks
